Import Numpy as np and see the version

In [1]:
import numpy as np
np.__version__

'1.15.1'

Create a 1D array of numbers from 0 to 9

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Create a 3x3 numpy array of all True's

In [3]:
np.ones((3,3), np.bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Extract all odd numbers from arr

In [4]:
arr = np.arange(10)

In [5]:
arr[arr % 2 != 0]

array([1, 3, 5, 7, 9])

Replace all odd numbers in arr with -1

In [6]:
arr = np.arange(10)

In [7]:
arr[arr % 2 != 0] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Replace all odd numbers in arr with -1 without changing arr

In [8]:
arr = np.arange(10)

In [9]:
np.where(arr%2==1, -1, arr)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Convert a 1D array to a 2D array with 2 rows

In [10]:
arr = np.arange(10)

In [11]:
arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Stack array a and b vertically

In [12]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [13]:
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Stack the arrays a and b horizontally

In [14]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [15]:
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

In [16]:
a = np.array([1,2,3])

In [17]:
np.concatenate((np.repeat(a,3),np.tile(a,3)))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

Get the commom items between a and b

In [18]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [19]:
np.intersect1d(a,b)

array([2, 4])

From array a remove all items present in array b

In [20]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [21]:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

Get the positions where elements of a and b match

In [22]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [23]:
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

Get all items between 5 and 10 from a

In [24]:
a = np.array([2,6,1,9,10,3,27])

In [25]:
a[np.where(np.logical_and(a>=5,a<=10))]

array([ 6,  9, 10])

Convert the function maxx that works on two scalars, to work on two arrays

In [26]:
def maxx(x, y):
    return np.maximum(x,y)

In [27]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
maxx(a, b)

array([6, 7, 9, 8, 9, 7, 5])

Swap columns 1 and 2 in the array arr

In [28]:
arr = np.arange(9).reshape(3,-1)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

Swap rows 1 and 2 in the array arr

In [30]:
arr = np.arange(9).reshape(3,-1)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

Reverse the rows of a 2D array arr

In [32]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

Reverse the columns of a 2D array arr

In [34]:
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10

In [35]:
np.random.uniform(5,10,(5,3))

array([[8.38457839, 8.06428141, 7.84997273],
       [6.46548642, 7.37732196, 7.44783953],
       [6.93355796, 7.90020255, 9.76853629],
       [6.43290177, 7.79462758, 8.87078159],
       [6.55740334, 8.70977094, 5.36938564]])

Print or show only 3 decimal places of the numpy array rand_arr

In [36]:
rand_arr = np.random.random((5,3))
rand_arr

array([[0.95903494, 0.69587336, 0.06914366],
       [0.70263351, 0.6854544 , 0.89850193],
       [0.78276673, 0.05515524, 0.19462217],
       [0.59411241, 0.7543295 , 0.58071223],
       [0.09562355, 0.21561654, 0.38851336]])

In [37]:
np.set_printoptions(precision=3)
rand_arr

array([[0.959, 0.696, 0.069],
       [0.703, 0.685, 0.899],
       [0.783, 0.055, 0.195],
       [0.594, 0.754, 0.581],
       [0.096, 0.216, 0.389]])

Pretty print rand_arr by supressing the scientific notation (like 1e10)

In [38]:
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[0.001, 0.001, 0.   ],
       [0.   , 0.001, 0.001],
       [0.001, 0.   , 0.001]])

In [39]:
np.set_printoptions(suppress=True)
rand_arr

array([[0.001, 0.001, 0.   ],
       [0.   , 0.001, 0.001],
       [0.001, 0.   , 0.001]])

Limit the number of items printed in python numpy array a to a maximum of 6 elements

In [40]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [41]:
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

Print the full numpy array a without truncating

In [42]:
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [43]:
np.set_printoptions(threshold=np.nan)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Import the iris dataset keeping the text intact

In [44]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_ld = np.genfromtxt(url, delimiter='.',dtype=object)
iris_ld

array([[b'5', b'1,3', b'5,1', b'4,0', b'2,Iris-setosa'],
       [b'4', b'9,3', b'0,1', b'4,0', b'2,Iris-setosa'],
       [b'4', b'7,3', b'2,1', b'3,0', b'2,Iris-setosa'],
       [b'4', b'6,3', b'1,1', b'5,0', b'2,Iris-setosa'],
       [b'5', b'0,3', b'6,1', b'4,0', b'2,Iris-setosa'],
       [b'5', b'4,3', b'9,1', b'7,0', b'4,Iris-setosa'],
       [b'4', b'6,3', b'4,1', b'4,0', b'3,Iris-setosa'],
       [b'5', b'0,3', b'4,1', b'5,0', b'2,Iris-setosa'],
       [b'4', b'4,2', b'9,1', b'4,0', b'2,Iris-setosa'],
       [b'4', b'9,3', b'1,1', b'5,0', b'1,Iris-setosa'],
       [b'5', b'4,3', b'7,1', b'5,0', b'2,Iris-setosa'],
       [b'4', b'8,3', b'4,1', b'6,0', b'2,Iris-setosa'],
       [b'4', b'8,3', b'0,1', b'4,0', b'1,Iris-setosa'],
       [b'4', b'3,3', b'0,1', b'1,0', b'1,Iris-setosa'],
       [b'5', b'8,4', b'0,1', b'2,0', b'2,Iris-setosa'],
       [b'5', b'7,4', b'4,1', b'5,0', b'4,Iris-setosa'],
       [b'5', b'4,3', b'9,1', b'3,0', b'4,Iris-setosa'],
       [b'5', b'1,3', b'5,1', b

Extract the text column species from the 1D iris imported in previous question

In [45]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=object)
species = np.unique(np.array([iris_1d[:, 4]]))
species

array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
      dtype=object)

Convert the 1D iris to 2D array iris_2d by omitting the species text field

In [46]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=object)

In [47]:
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

Find the mean, median, standard devation of iri's sepallength (1st column)

In [48]:
sepallength = np.genfromtxt(url, delimiter='.', dtype=np.float, usecols=[0])
sepallength

array([5., 4., 4., 4., 5., 5., 4., 5., 4., 4., 5., 4., 4., 4., 5., 5., 5.,
       5., 5., 5., 5., 5., 4., 5., 4., 5., 5., 5., 5., 4., 4., 5., 5., 5.,
       4., 5., 5., 4., 4., 5., 5., 4., 4., 5., 5., 4., 5., 4., 5., 5., 7.,
       6., 6., 5., 6., 5., 6., 4., 6., 5., 5., 5., 6., 6., 5., 6., 5., 5.,
       6., 5., 5., 6., 6., 6., 6., 6., 6., 6., 6., 5., 5., 5., 5., 6., 5.,
       6., 6., 6., 5., 5., 5., 6., 5., 5., 5., 5., 5., 6., 5., 5., 6., 5.,
       7., 6., 6., 7., 4., 7., 6., 7., 6., 6., 6., 5., 5., 6., 6., 7., 7.,
       6., 6., 5., 7., 6., 6., 7., 6., 6., 6., 7., 7., 7., 6., 6., 6., 7.,
       6., 6., 6., 6., 6., 6., 5., 6., 6., 6., 6., 6., 6., 5.])

In [49]:
print(np.mean(sepallength))
print(np.median(sepallength))
print(np.std(sepallength))

5.386666666666667
5.0
0.8389411315594332


Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.

In [50]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [51]:
np.array([(a - np.min(sepallength))/(np.max(sepallength) - np.min(sepallength)) for a in sepallength])

array([0.222, 0.167, 0.111, 0.083, 0.194, 0.306, 0.083, 0.194, 0.028,
       0.167, 0.306, 0.139, 0.139, 0.   , 0.417, 0.389, 0.306, 0.222,
       0.389, 0.222, 0.306, 0.222, 0.083, 0.222, 0.139, 0.194, 0.194,
       0.25 , 0.25 , 0.111, 0.139, 0.306, 0.25 , 0.333, 0.167, 0.194,
       0.333, 0.167, 0.028, 0.222, 0.194, 0.056, 0.028, 0.194, 0.222,
       0.139, 0.222, 0.083, 0.278, 0.194, 0.75 , 0.583, 0.722, 0.333,
       0.611, 0.389, 0.556, 0.167, 0.639, 0.25 , 0.194, 0.444, 0.472,
       0.5  , 0.361, 0.667, 0.361, 0.417, 0.528, 0.361, 0.444, 0.5  ,
       0.556, 0.5  , 0.583, 0.639, 0.694, 0.667, 0.472, 0.389, 0.333,
       0.333, 0.417, 0.472, 0.306, 0.472, 0.667, 0.556, 0.361, 0.333,
       0.333, 0.5  , 0.417, 0.194, 0.361, 0.389, 0.389, 0.528, 0.222,
       0.389, 0.556, 0.417, 0.778, 0.556, 0.611, 0.917, 0.167, 0.833,
       0.667, 0.806, 0.611, 0.583, 0.694, 0.389, 0.417, 0.583, 0.611,
       0.944, 0.944, 0.472, 0.722, 0.361, 0.944, 0.556, 0.667, 0.806,
       0.528, 0.5  ,

Compute the softmax score of speallength

In [52]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [53]:
def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

print(softmax(sepallength))

[0.002 0.002 0.001 0.001 0.002 0.003 0.001 0.002 0.001 0.002 0.003 0.002
 0.002 0.001 0.004 0.004 0.003 0.002 0.004 0.002 0.003 0.002 0.001 0.002
 0.002 0.002 0.002 0.002 0.002 0.001 0.002 0.003 0.002 0.003 0.002 0.002
 0.003 0.002 0.001 0.002 0.002 0.001 0.001 0.002 0.002 0.002 0.002 0.001
 0.003 0.002 0.015 0.008 0.013 0.003 0.009 0.004 0.007 0.002 0.01  0.002
 0.002 0.005 0.005 0.006 0.004 0.011 0.004 0.004 0.007 0.004 0.005 0.006
 0.007 0.006 0.008 0.01  0.012 0.011 0.005 0.004 0.003 0.003 0.004 0.005
 0.003 0.005 0.011 0.007 0.004 0.003 0.003 0.006 0.004 0.002 0.004 0.004
 0.004 0.007 0.002 0.004 0.007 0.004 0.016 0.007 0.009 0.027 0.002 0.02
 0.011 0.018 0.009 0.008 0.012 0.004 0.004 0.008 0.009 0.03  0.03  0.005
 0.013 0.004 0.03  0.007 0.011 0.018 0.007 0.006 0.008 0.018 0.022 0.037
 0.008 0.007 0.006 0.03  0.007 0.008 0.005 0.013 0.011 0.013 0.004 0.012
 0.011 0.011 0.007 0.009 0.007 0.005]


Fin the 5th and 95th percentile of iri's sepallength

In [54]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [55]:
np.percentile(sepallength,[5,95])

array([4.6  , 7.255])

Insert np.nan values at 20 random positions in iris_2d dataset

In [56]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
iris_2d.shape

(150, 5)

In [57]:
iris_2d[np.random.randint(0,150,20),np.random.randint(0,5,20)] = np.nan
iris_2d

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa'],
       [nan, b'3.9', b'1.7', b'0.4', b'Iris-setosa'],
       [b'4.6', nan, b'1.4', b'0.3', b'Iris-setosa'],
       [b'5.0', b'3.4', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.1', b'1.5', b'0.1', b'Iris-setosa'],
       [b'5.4', b'3.7', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.4', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.0', b'1.4', b'0.1', b'Iris-setosa'],
       [b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'],
       [b'5.8', b'4.0', b'1.2', b'0.2', b'Iris-setosa'],
       [b'5.7', b'4.4', b'1.5', b'0.4', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.3', b'0.4', b'Iris-setosa'],
       [b'5.1', b'3.5', b'1.4', b'0.3

Find the number and position of missing values in iris_2d's sepallength (1st column)

In [58]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [59]:
print(np.isnan(iris_2d[:,0]).sum())
print(np.argwhere(np.isnan(iris_2d[:,0])))

5
[[ 53]
 [ 65]
 [114]
 [118]
 [143]]


Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [60]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [61]:
iris_2d[np.logical_and(iris_2d[:,2] > 1.5,iris_2d[:,0] < 5)]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

Select the rows of iris_2d that does not have any nan value.

In [62]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [63]:
iris_2d[[~np.any(np.isnan(a)) for a in iris_2d]]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.7, 3.8, 1.7, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3

Find the correlation between SepalLength(1st column) and PetalLength(3rd column) in iris_2d

In [64]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [65]:
np.corrcoef(iris_2d[:,0],iris_2d[:,2])[0,1]

0.8717541573048714

Find out if iris_2d has any missing values.

In [66]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [67]:
np.any(np.isnan(iris_2d))

False

Replace all ccurrences of nan with 0 in numpy array

In [68]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [69]:
iris_2d[np.isnan(iris_2d)] = 0

Find the unique values and the count of unique values in iris's species

In [70]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [71]:
np.unique(iris[:,-1], return_counts=True)

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype=object), array([50, 50, 50], dtype=int64))

Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:

In [72]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [73]:
petal_length_bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5, 10])
label_map = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}
petal_length_cat = [label_map[x] for x in petal_length_bin]

Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

In [74]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [75]:
volume = [(np.pi * petal * (sepal**2))/3 for sepal,petal in iris_2d[:,[0,2]].astype('float')]
np.c_[iris_2d,np.array(volume)]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa',
        38.13265162927291],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa',
        35.200498485922445],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa', 30.0723720777127],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa',
        33.238050274980004],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa',
        36.65191429188092],
       [b'5.4', b'3.9', b'1.7', b'0.4', b'Iris-setosa',
        51.911677007917746],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa',
        31.022180256648003],
       [b'5.0', b'3.4', b'1.5', b'0.2', b'Iris-setosa',
        39.269908169872416],
       [b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa',
        28.38324242763259],
       [b'4.9', b'3.1', b'1.5', b'0.1', b'Iris-setosa',
        37.714819806345474],
       [b'5.4', b'3.7', b'1.5', b'0.2', b'Iris-setosa',
        45.80442088933919],
       [b'4.8', b'3.4', b'1.6', b'0.2', b'Iris-setosa',
        38.603890527311

Randomly sample iris's species such that setose is twice the number of versicolor and virginica

In [76]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [77]:
species = iris[:, -1]
a = np.unique(species)
species_out = np.random.choice(a,150,p=[0.5,0.25,0.25])
np.unique(species_out, return_counts=True) # extracode

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype=object), array([71, 40, 39], dtype=int64))

What is the value of second longest petallength of species setosa

In [78]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [79]:
np.unique(np.sort(iris[iris[:,4] == b'Iris-setosa', [2]].astype('float')))[-2]

1.7

Sort the iris dataset based on sepallength column.

In [80]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [81]:
iris[iris[:,0].argsort()]

array([[b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'],
       [b'4.4', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.4', b'3.0', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.5', b'2.3', b'1.3', b'0.3', b'Iris-setosa'],
       [b'4.6', b'3.6', b'1.0', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'],
       [b'4.6', b'3.2', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.0', b'1.4', b'0.1', b'Iris-setosa'],
       [b'4.8', b'3.0', b'1.4', b'0.3', b'Iris-setosa'],
       [b'4.8', b'3.4', b'1.9', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.4', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.1', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.9', b'2.4', b'3.3', b'1.0', b'Iris-versicolor'],
       [b'4.9', b'2.5', b'4

Find the most frequent value of petal length (3rd column) in iris dataset.

In [82]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [83]:
vals, counts = np.unique(iris[:,2],return_counts=True)
vals[np.argmax(counts)]

b'1.5'

Find the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of iris dataset.

In [84]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float')

In [85]:
np.argwhere(iris[:, 3] > 1)[0]

array([50], dtype=int64)

From the array a, replace all values greater than 30 to 30 and less than 10 to 10.

In [86]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)
a

array([27.627, 14.64 , 21.801, 42.394,  1.231,  6.957, 33.867, 41.467,
        7.699, 29.18 , 44.675, 11.251, 10.081,  6.31 , 11.765, 48.953,
       40.772,  9.425, 40.995, 14.43 ])

In [87]:
np.clip(a,10,30)

array([27.627, 14.64 , 21.801, 30.   , 10.   , 10.   , 30.   , 30.   ,
       10.   , 29.18 , 30.   , 11.251, 10.081, 10.   , 11.765, 30.   ,
       30.   , 10.   , 30.   , 14.43 ])

Get the positions of top 5 maximum values in a given array a.

In [88]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)

In [89]:
np.argsort(a)[-5:]

array([18,  7,  3, 10, 15], dtype=int64)

Compute the counts of unique values row-wise.

In [90]:
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr

array([[ 9,  9,  4,  8,  8,  1,  5,  3,  6,  3],
       [ 3,  3,  2,  1,  9,  5,  1, 10,  7,  3],
       [ 5,  2,  6,  4,  5,  5,  4,  8,  2,  2],
       [ 8,  8,  1,  3, 10, 10,  4,  3,  6,  9],
       [ 2,  1,  8,  7,  3,  1,  9,  3,  6,  2],
       [ 9,  2,  6,  5,  3,  9,  4,  6,  1, 10]])

In [91]:
result = []
for a in arr:
    dic = dict(zip(range(1, 11), np.repeat(0,10)))
    index, counts = np.unique(a, return_counts = True)
    for b,c in zip(index,counts):
        dic.update({b:c})
    result.append(list(dic.values()))
np.array(result, np.uint8)

array([[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
       [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
       [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
       [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
       [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]], dtype=uint8)

Convert array_of_arrays into a flat linear 1d array.

In [92]:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
array_of_arrays

array([array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])],
      dtype=object)

In [93]:
np.hstack(array_of_arrays)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Compute the one-hot encodings (dummy binary variables for each unique value in the array)

In [94]:
np.random.seed(101) 
arr = np.random.randint(1,4, size=8)
arr

array([2, 3, 2, 2, 2, 1, 1, 1])

In [95]:
result = []
for a in arr:
    res = np.zeros(3)
    res[a-1] = 1
    result = np.concatenate((result,res))
result.reshape(-1,3)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

Create row numbers grouped by a categorical variable. Use the following sample from iris species as input.

In [96]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))
species_small

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica'], dtype='<U15')

In [97]:
print([i for val in np.unique(species_small) for i, grp in enumerate(species_small[species_small==val])])

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 6, 7, 8]


Create group ids based on a given categorical variable. Use the following sample from iris species as input.

In [98]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))
species_small

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica'], dtype='<U15')

In [99]:
index = enumerate(np.unique(species_small))
for a,b in index:
    species_small[species_small == b] = a
species_small.astype('int')

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2])

Create the ranks for the given numeric array a.

In [100]:
np.random.seed(10)
a = np.random.randint(20, size=10)
a

array([ 9,  4, 15,  0, 17, 16, 17,  8,  9,  0])

In [101]:
a[np.argsort(a)] = range(10)

Create a rank array of the same shape as a given numeric array a.

In [102]:
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
a

array([[ 9,  4, 15,  0, 17],
       [16, 17,  8,  9,  0]])

In [103]:
np.concatenate(a).argsort().argsort().reshape(a.shape)

array([[4, 2, 6, 0, 8],
       [7, 9, 3, 5, 1]], dtype=int64)

Compute the maximum for each row in the given array.

In [104]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a

array([[9, 9, 4],
       [8, 8, 1],
       [5, 3, 6],
       [3, 3, 3],
       [2, 1, 9]])

In [105]:
np.amax(a,axis=1) # or [max(b) for b in a]

array([9, 8, 6, 3, 9])

Compute the min-by-max for each row for given 2d numpy array.

In [106]:
np.amin(a,axis=1)/np.amax(a,axis=1)

array([0.444, 0.125, 0.5  , 1.   , 0.111])

Find the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as True. First time occurrences should be False.

In [107]:
np.random.seed(100)
a = np.random.randint(0, 5, 10)
a

array([0, 0, 3, 0, 2, 4, 2, 2, 2, 2])

In [108]:
out = np.full(a.shape[0], True)
unique_positions = np.unique(a, return_index=True)[1]
out[unique_positions] = False
out

array([False,  True, False,  True, False, False,  True,  True,  True,
        True])

Find the mean of a numeric column grouped by a categorical column in a 2D numpy array

In [109]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [110]:
[np.mean(iris[iris[:,-1] == s][:,1].astype('float')) for s in np.unique(iris[:,-1])]

[3.418, 2.7700000000000005, 2.974]

Import the image from the following URL and convert it to a numpy array.

In [111]:
URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'

In [112]:
from io import BytesIO
from PIL import Image
import PIL, requests
response = requests.get(URL)

In [113]:
I = Image.open(BytesIO(response.content))
I = I.resize([150,150])
arr = np.asarray(I)

Drop all nan values from a 1D numpy array

In [114]:
arr = np.array([1,2,3,np.nan,5,6,7,np.nan])

In [115]:
arr[~np.isnan(arr)]

array([1., 2., 3., 5., 6., 7.])

Compute the euclidean distance between two arrays a and b

In [116]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

In [117]:
np.linalg.norm(a-b)

6.708203932499369

Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.

In [118]:
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])

In [119]:
doublediff = np.diff(np.sign(np.diff(a)))
peak_locations = np.where(doublediff == -2)[0] + 1
peak_locations

array([2, 5], dtype=int64)

Subtraia a matriz 1d da matriz b_1d2d a_2d, de forma que cada item de b_1dsubtraia da respectiva linha de a_2d.

In [120]:
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])

In [121]:
a_2d - b_1d[:, None]

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

Encontre o índice da 5ª repetição do número 1 em x.

In [122]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

In [123]:
np.argsort(x)[4]

8